nav:
  - Boîte à outils:
    - "outils/index.md"
    - Exercices automatiques:
      - "outils/complement-a-2.md"
      - "outils/utf-8.md"
  - Challenges:
    - "challenges/[0-9]_*"
    - Liste complète:
      - "challenges/*/enonce.md"
  - Concours: https://docs.google.com/spreadsheets/d/1vklCIauWj8BNkNmgraetFxHo3Oh3a8i_OZrc0XGr0wI/
